<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { json, request } from '../api/client'

const { t } = useI18n()
const client = useQueryClient()
const rulesQuery = useQuery({ queryKey: ['button-rules'], queryFn: () => request<any[]>('/api/v1/button-rules') })
const open = ref(false)
const editing = ref<number | null>(null)
const form = reactive({ name: '', enabled: false, source_chats: [] as (string | number)[], button_texts: [] as string[], match_mode: 'exact', delay: 0, click_all_matches: false })
const text = reactive({ sources: '', buttons: '' })
function values(value: string) { return value.split('\n').map(v => v.trim()).filter(Boolean) }
function chats(value: string) { return values(value).map(v => /^-?\d+$/.test(v) ? Number(v) : v) }
function create() { Object.assign(form, { name: '', enabled: false, source_chats: [], button_texts: [], match_mode: 'exact', delay: 0, click_all_matches: false }); Object.assign(text, { sources: '', buttons: '' }); editing.value = null; open.value = true }
function edit(index: number) { const value = structuredClone(rulesQuery.data.value?.[index]); Object.assign(form, value); text.sources = value.source_chats.join('\n'); text.buttons = value.button_texts.join('\n'); editing.value = index; open.value = true }
const save = useMutation({ mutationFn: () => { const payload = { ...form, source_chats: chats(text.sources), button_texts: values(text.buttons) }; return request(editing.value === null ? '/api/v1/button-rules' : `/api/v1/button-rules/${editing.value}`, json(editing.value === null ? 'POST' : 'PUT', payload)) }, onSuccess: () => { open.value = false; client.invalidateQueries({ queryKey: ['button-rules'] }) } })
const remove = useMutation({ mutationFn: (index: number) => request(`/api/v1/button-rules/${index}`, json('DELETE')), onSuccess: () => client.invalidateQueries({ queryKey: ['button-rules'] }) })
function removeRule(index: number) { if (window.confirm(t('common.confirmDelete'))) remove.mutate(index) }
</script>

<template><section><header class="page-heading"><div><p class="eyebrow">INTERACTION ENGINE / USER SESSION</p><h1>{{ t('automations.title') }}</h1><p>{{ t('automations.subtitle') }}</p></div><button class="primary-button compact" @click="create">{{ t('automations.new') }} ＋</button></header><article class="panel table-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>AUTOMATION</th><th>STATUS</th><th>SOURCES</th><th>MATCH</th><th>BUTTONS</th><th>ACTIONS</th></tr></thead><tbody><tr v-for="(rule,index) in rulesQuery.data.value" :key="rule.name"><td><strong>{{ rule.name }}</strong><br>{{ rule.delay }}s delay</td><td><span class="tag" :class="{off:!rule.enabled}">{{ rule.enabled ? t('common.enabled') : t('common.disabled') }}</span></td><td>{{ rule.source_chats.join(', ') || '—' }}</td><td>{{ rule.match_mode }}<br>{{ rule.click_all_matches ? 'ALL MATCHES' : 'FIRST MATCH' }}</td><td>{{ rule.button_texts.join(' · ') || '—' }}</td><td><div class="action-row"><button class="icon-action" @click="edit(index)">{{ t('common.edit') }}</button><button class="icon-action" @click="removeRule(index)">{{ t('common.delete') }}</button></div></td></tr></tbody></table><p v-if="!rulesQuery.data.value?.length" class="empty-state">{{ t('common.noData') }}</p></div></article><div v-if="open" class="drawer" @click.self="open=false"><form class="drawer-panel" @submit.prevent="save.mutate()"><div class="drawer-heading"><div><p class="eyebrow">AUTOMATION EDITOR</p><h2>{{ editing === null ? t('automations.new') : form.name }}</h2></div><button type="button" class="drawer-close" @click="open=false">×</button></div><div class="form-grid"><label class="full">NAME<input v-model="form.name" required></label><label class="full">SOURCE CHATS<textarea v-model="text.sources" rows="4" placeholder="@example_bot"></textarea></label><label class="full">BUTTON TEXT / PATTERNS<textarea v-model="text.buttons" rows="5"></textarea></label><label>MATCH MODE<select v-model="form.match_mode"><option value="exact">Exact</option><option value="contains">Contains</option><option value="regex">Regex</option></select></label><label>DELAY / SEC<input v-model.number="form.delay" type="number" min="0" max="30" step=".1"></label></div><div class="form-section check-row"><label><input v-model="form.enabled" type="checkbox">{{ t('common.enabled') }}</label><label><input v-model="form.click_all_matches" type="checkbox">Click all matches</label></div><p v-if="save.error.value" class="form-error">{{ save.error.value.message }}</p><div class="form-section control-row"><button type="button" class="ghost-button" @click="open=false">{{ t('common.cancel') }}</button><button class="primary-button compact">{{ t('common.save') }} ↗</button></div></form></div></section></template>
