<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { json, request } from '../api/client'

const { t } = useI18n()
const queryClient = useQueryClient()
const rulesQuery = useQuery({ queryKey: ['rules'], queryFn: () => request<any[]>('/api/v1/rules') })
const editorOpen = ref(false)
const editingIndex = ref<number | null>(null)

const blank = () => ({ name: '', enabled: true, source_chats: [] as (string | number)[], target_chats: [] as (string | number)[], filters: { mode: 'whitelist', keywords: [] as string[], regex_patterns: [] as string[], media_types: [] as string[], max_file_size: 0, min_file_size: 0 }, ignore: { user_ids: [] as number[], keywords: [] as string[] }, forwarding: { preserve_format: true, add_source_info: true, delay: 0.5, force_forward: false, hide_sender: false, deduplicate: false, deduplicate_window: 3600 } })
const form = reactive(blank())
const text = reactive({ sources: '', targets: '', keywords: '', regex: '', ignoredUsers: '', ignoredKeywords: '' })

function lines(value: string): (string | number)[] { return value.split('\n').map(v => v.trim()).filter(Boolean).map(v => /^-?\d+$/.test(v) ? Number(v) : v) }
function openNew() { Object.assign(form, blank()); Object.assign(text, { sources: '', targets: '', keywords: '', regex: '', ignoredUsers: '', ignoredKeywords: '' }); editingIndex.value = null; editorOpen.value = true }
function openEdit(index: number) { const rule = structuredClone(rulesQuery.data.value?.[index]); Object.assign(form, rule); Object.assign(text, { sources: rule.source_chats.join('\n'), targets: rule.target_chats.join('\n'), keywords: rule.filters.keywords.join('\n'), regex: rule.filters.regex_patterns.join('\n'), ignoredUsers: rule.ignore.user_ids.join('\n'), ignoredKeywords: rule.ignore.keywords.join('\n') }); editingIndex.value = index; editorOpen.value = true }

const saveMutation = useMutation({ mutationFn: async () => { const payload = structuredClone(form); payload.source_chats = lines(text.sources); payload.target_chats = lines(text.targets); payload.filters.keywords = lines(text.keywords).map(String); payload.filters.regex_patterns = lines(text.regex).map(String); payload.ignore.user_ids = lines(text.ignoredUsers).filter(v => typeof v === 'number') as number[]; payload.ignore.keywords = lines(text.ignoredKeywords).map(String); const path = editingIndex.value === null ? '/api/v1/rules' : `/api/v1/rules/${editingIndex.value}`; return request(path, json(editingIndex.value === null ? 'POST' : 'PUT', payload)) }, onSuccess: async () => { editorOpen.value = false; await queryClient.invalidateQueries({ queryKey: ['rules'] }) } })
const deleteMutation = useMutation({ mutationFn: (index: number) => request(`/api/v1/rules/${index}`, json('DELETE')), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['rules'] }) })
const enabledCount = computed(() => rulesQuery.data.value?.filter(rule => rule.enabled).length ?? 0)
function removeRule(index: number) { if (window.confirm(t('common.confirmDelete'))) deleteMutation.mutate(index) }
</script>

<template>
  <section><header class="page-heading"><div><p class="eyebrow">ROUTING MATRIX / {{ enabledCount }} ACTIVE</p><h1>{{ t('rules.title') }}</h1><p>{{ t('rules.subtitle') }}</p></div><button class="primary-button compact" @click="openNew">{{ t('rules.new') }} <b>＋</b></button></header>
    <article class="panel table-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>RULE</th><th>STATUS</th><th>SOURCE</th><th>TARGET</th><th>FILTER</th><th>{{ t('common.actions').toUpperCase() }}</th></tr></thead><tbody><tr v-for="(rule, index) in rulesQuery.data.value" :key="rule.name"><td><strong>{{ rule.name }}</strong><br><span>{{ rule.forwarding.delay }}s delay</span></td><td><span class="tag" :class="{ off: !rule.enabled }">{{ rule.enabled ? t('common.enabled') : t('common.disabled') }}</span></td><td>{{ rule.source_chats.join(', ') || '—' }}</td><td>{{ rule.target_chats.join(', ') || '—' }}</td><td>{{ rule.filters.mode }} · {{ rule.filters.keywords.length + rule.filters.regex_patterns.length }}</td><td><div class="action-row"><button class="icon-action" @click="openEdit(index)">{{ t('common.edit') }}</button><button class="icon-action" @click="removeRule(index)">{{ t('common.delete') }}</button></div></td></tr></tbody></table><p v-if="!rulesQuery.data.value?.length" class="empty-state">{{ t('common.noData') }}</p></div></article>
    <div v-if="editorOpen" class="drawer" @click.self="editorOpen = false"><form class="drawer-panel" @submit.prevent="saveMutation.mutate()"><div class="drawer-heading"><div><p class="eyebrow">RULE EDITOR</p><h2>{{ editingIndex === null ? t('rules.new') : form.name }}</h2></div><button type="button" class="drawer-close" @click="editorOpen = false">×</button></div><div class="form-grid"><label class="full">NAME<input v-model="form.name" required /></label><label class="full">SOURCE CHATS<textarea v-model="text.sources" rows="3" placeholder="-100123…&#10;@channel"></textarea></label><label class="full">TARGET CHATS<textarea v-model="text.targets" rows="3"></textarea></label><label>FILTER MODE<select v-model="form.filters.mode"><option value="whitelist">Whitelist</option><option value="blacklist">Blacklist</option></select></label><label>DELAY / SEC<input v-model.number="form.forwarding.delay" type="number" min="0" step="0.1" /></label><label>KEYWORDS<textarea v-model="text.keywords" rows="4"></textarea></label><label>REGEX PATTERNS<textarea v-model="text.regex" rows="4"></textarea></label><label>IGNORED USERS<textarea v-model="text.ignoredUsers" rows="3"></textarea></label><label>IGNORED KEYWORDS<textarea v-model="text.ignoredKeywords" rows="3"></textarea></label></div><div class="form-section"><h3>FORWARDING BEHAVIOUR</h3><div class="check-row"><label><input v-model="form.enabled" type="checkbox" />{{ t('common.enabled') }}</label><label><input v-model="form.forwarding.preserve_format" type="checkbox" />Preserve format</label><label><input v-model="form.forwarding.add_source_info" type="checkbox" />Source info</label><label><input v-model="form.forwarding.force_forward" type="checkbox" />Force upload</label><label><input v-model="form.forwarding.hide_sender" type="checkbox" />Hide sender</label><label><input v-model="form.forwarding.deduplicate" type="checkbox" />Deduplicate</label></div></div><p v-if="saveMutation.error.value" class="form-error">{{ saveMutation.error.value.message }}</p><div class="form-section control-row"><button type="button" class="ghost-button" @click="editorOpen = false">{{ t('common.cancel') }}</button><button class="primary-button compact">{{ t('common.save') }} ↗</button></div></form></div>
  </section>
</template>
